"""Canonical and operational hunting contracts."""
from hunting.contracts.abduction import AbductionRuntime
from hunting.contracts.capabilities import (
    CapabilityDescriptor,
    CapabilityMatcher,
    MatchResult,
    ProviderCapabilityCatalog,
)
from hunting.contracts.case_graph import (
    ActionCandidate,
    EvidenceGoal,
    EvidenceSubgraph,
    FieldRole,
    GraphEdge,
    GraphNode,
    InvestigationCase,
    InvestigationGraph,
    InvestigationUnknown,
    NodeStatus,
    NodeType,
    RelationProof,
    RelationStatus,
    RelationType,
)
from hunting.contracts.cells import Cell, CellState, ProviderScope
from hunting.contracts.conflicts import Conflict, HumanInput
from hunting.contracts.coverage import CoverageBound, RequirementCoverage, SamplingStats
from hunting.contracts.entities import (
    ANY,
    AnyEntity,
    Domain,
    EntityKind,
    EntityRef,
    File,
    Host,
    IPAddress,
    Process,
    User,
)
from hunting.contracts.expectations import (
    EvidenceRequirement,
    Expectation,
    FieldOp,
    FieldPredicate,
    TestStatus,
)
from hunting.contracts.explanations import (
    Attribution,
    AttributionStatus,
    Explanation,
    ExplanationClass,
    ExplanationOrigin,
    ExplanationStatus,
)
from hunting.contracts.hunt import (
    EvidenceAssessment,
    EvidenceCard,
    EvidenceRequirementSpec,
    EvidenceRequirementV4,
    FinalHuntAccount,
    HuntObjective,
    HuntOutcome,
    HuntRequest,
    HuntRequestKind,
    HuntState,
    Hypothesis,
    HypothesisOrigin,
    HypothesisStatus,
    LogicalQueryPlan,
    NativeQueryPlan,
    QueryPlan,
    RequestedObject,
    RequirementStatus,
    SemanticEvidenceRequirement,
    SemanticHuntIntent,
    StoppingDecision,
    SubjectEntity,
    TimePolicy,
)
from hunting.contracts.observations import (
    EpistemicType,
    Observation,
    Provenance,
    SemanticType,
    TaintLabel,
)
from hunting.contracts.queries import (
    Diagnostic,
    DiagnosticClass,
    ProviderOperation,
    Query,
    QueryOutcome,
    QueryResult,
)
from hunting.contracts.state import (
    Alert,
    DarkSource,
    Disposition,
    FinalAccount,
    InvestigationState,
    Seed,
    TerminalState,
    TimeWindow,
)

__all__ = [
    # v5 Investigation Case Graph Contracts
    "InvestigationCase",
    "InvestigationGraph",
    "GraphNode",
    "GraphEdge",
    "FieldRole",
    "NodeType",
    "RelationType",
    "NodeStatus",
    "RelationStatus",
    "InvestigationUnknown",
    "EvidenceGoal",
    "ActionCandidate",
    "RelationProof",
    "EvidenceSubgraph",
    # v4 Canonical Hunt Contracts
    "HuntRequest",
    "HuntRequestKind",
    "TimePolicy",
    "HuntObjective",
    "Hypothesis",
    "HypothesisOrigin",
    "HypothesisStatus",
    "EvidenceRequirementV4",
    "EvidenceRequirementSpec",
    "RequirementStatus",
    "QueryPlan",
    "LogicalQueryPlan",
    "NativeQueryPlan",
    "EvidenceCard",
    "EvidenceAssessment",
    "HuntOutcome",
    "StoppingDecision",
    "HuntState",
    "FinalHuntAccount",
    # Operational Contracts
    "Cell",
    "CellState",
    "ProviderScope",
    "Observation",
    "EpistemicType",
    "TaintLabel",
    "SemanticType",
    "Provenance",
    "EvidenceRequirement",
    "Expectation",
    "FieldPredicate",
    "FieldOp",
    "TestStatus",
    "Explanation",
    "ExplanationClass",
    "ExplanationStatus",
    "ExplanationOrigin",
    "Attribution",
    "AttributionStatus",
    "Query",
    "QueryResult",
    "QueryOutcome",
    "ProviderOperation",
    "Diagnostic",
    "DiagnosticClass",
    "CoverageBound",
    "RequirementCoverage",
    "SamplingStats",
    "Conflict",
    "HumanInput",
    "AbductionRuntime",
    "CapabilityDescriptor",
    "ProviderCapabilityCatalog",
    "CapabilityMatcher",
    "MatchResult",
    # Entities
    "EntityRef",
    "EntityKind",
    "Host",
    "User",
    "Process",
    "IPAddress",
    "Domain",
    "File",
    "ANY",
    "AnyEntity",
    # Legacy Compatibility Contracts
    "Alert",
    "Seed",
    "TimeWindow",
    "InvestigationState",
    "FinalAccount",
    "Disposition",
    "TerminalState",
    "DarkSource",
    "SubjectEntity",
    "RequestedObject",
    "SemanticEvidenceRequirement",
    "SemanticHuntIntent",
]
