"""Expectations — testable predictions generated by explanations.

4 fields proposed by LLM: predicted_observation, entity_ref, event_family, field_predicate
4 fields derived deterministically: source, time_window, falsification_condition, discriminates

Expectation.entity_ref may NEVER be AnyEntity (ANY).
"""
from __future__ import annotations
from dataclasses import dataclass, field
from enum import Enum

from hunting.contracts.entities import EntityRef
from hunting.contracts.cells import EventFamily


class TestStatus(str, Enum):
    """Result of testing an expectation against query results.

    Five statuses — each maps to a distinct failure mode:
      UNTESTED     — not yet queried
      CONFIRMED    — predicate satisfied (valid even on a truncated result)
      REFUTED      — genuinely contradicted on COMPLETE, OBSERVABLE telemetry
                     → weakens the owning explanation
      UNTESTABLE   — outcome UNKNOWN, or no source/window can resolve it
                     → does NOT weaken (absence of evidence ≠ evidence of absence)
      INCONCLUSIVE — field not populated in returned rows, OR result was truncated
                     and the predicate was not matched
                     → does NOT weaken
    """
    UNTESTED = "untested"
    CONFIRMED = "confirmed"
    REFUTED = "refuted"
    UNTESTABLE = "untestable"
    INCONCLUSIVE = "inconclusive"


class FieldOp(str, Enum):
    """Operations for field predicates."""
    EQUALS = "equals"
    CONTAINS = "contains"
    EXISTS = "exists"
    ABSENT = "absent"


@dataclass(frozen=True)
class FieldPredicate:
    """A testable condition on a specific field in a query result."""
    field: str
    op: FieldOp
    value: str = ""  # not used for EXISTS / ABSENT


@dataclass
class Expectation:
    """A testable prediction made by an explanation.

    Invariants:
      - entity_ref may NEVER be AnyEntity (ANY)
      - event_family must be from the closed EventFamily enum, validated against registry
      - ubiquitous fields (ts, host, pid, user) may NOT be the sole discriminator
    """
    id: str
    owner_explanation_id: str
    predicted_observation: str     # LLM free-text description of what to expect
    entity_ref: EntityRef          # NEVER AnyEntity
    event_family: EventFamily      # closed enum — LLM picks, validated deterministically
    field_predicate: FieldPredicate
    source: str                    # deterministic: registry lookup
    time_window: str               # deterministic: anchor_windows, clipped to coverage
    falsification_condition: str   # deterministic: mechanical inverse of field_predicate
    discriminates: list[str] = field(default_factory=list)  # explanation IDs discriminated
    test_status: TestStatus = TestStatus.UNTESTED
